### ISSUE TITLE
Authenticator and Wordpress App for Android have a issue with XMLRPC

### ISSUE THREAD

**Issue by rastarevolution** [bueltge/Authenticator#17]
Hi,
ich habe das Problem, dass ich den Authenticator aktiviert habe und dass der Zugriff mit der Wordpress App für Android nicht mehr funktioniert.
Wenn ich den Authenticator deaktiviere, habe ich wieder Zugriff auf meinen Blog.
Unter Einstellungen-->Lesen-->Disable XMLRPC Interface? habe ich das Häckchen entfernt.

Ist dieses Problem bekannt oder bin ich nur zu blöd die Einstellungen korrekt vorzunehmen? ;-)
## Vielen Dank im Voraus für die Antworten! :-)

Hi,
I have the problem that I have enabled the authenticator and that the access to the WordPress app for Android does not work anymore.
If I disable the authenticator, I regain access to my blog.
Under Settings -> Reading -> Disable XMLRPC interface? I have the tick removed.

Is this a known problem or am I just too stupid to make the settings correct? ;-)

Thanks in advance for the answers! :-)

**Comment by Raymond1970** [comment]
Hello all,

Maybe a little bit late, but I noticed that I still have the issue, als when using verion 1.2.1.
Can one please assist

**Comment by bueltge** [comment]
XMLRPC is inactive on WP default. Do you have active this surface? Please check the options in the "Reading" Settings - `wp-admin/options-reading.php`. The entry "Disable XMLRPC Interface?" is the key for this feature.
