### ISSUE TITLE
An additional filter to bypass the plugin

### ISSUE THREAD

**Issue by websupporter** [bueltge/Authenticator#25]
If the plugin would provide a general bypass filter (e.g. [here](https://github.com/bueltge/Authenticator/blob/master/authenticator.php#L249)), other plugins could hook in to provide some own rules when to bypass the filter. Right now, we only allow to filter in in case of `is_feed()`.

Use case:
Legacy project which has a special, quirky way to output a selfmade feed in case of a specific GET parameter given.

**Comment by bueltge** [comment]
Nice enhancement, would you @websupporter send a pull request?

**Comment by bueltge** [comment]
Thanks @websupporter Maybe you can enhance the readme for this new feature?

**Comment by Biont** [comment]
Could you please release this?

**Comment by bueltge** [comment]
@Biont I will do that today.
