### ISSUE TITLE
Please update the plugin for security reasons

### ISSUE THREAD

**Issue by alexseboe** [bueltge/Authenticator#26]
Hello, thank you for this great plugin. 

The last update was now 9 month ago. Could you please check the plugin security and its compatibility to new Wordpress Versions and update the plugin. Many people might decativate the plugin because of the long time it was not updates, even if it is secure.

Thank's a lot
Alex

**Comment by bueltge** [comment]
Hi Alex.
Thanks a lot for usage of the plugin and the hint about security. However we haven't an hint about problems, security topics. The plugins works also under each version, include the next on 4.8. I will update the readme for find this faster on the repository.

**Comment by alexseboe** [comment]
Hello,

Sounds really good. However, the plugin info sais: Warning: This plugin has not been tested with your current version of WordPress. 

So maybe, if you just do a minor update to confirm that the plugin was tested with the current version and include the information in the readme.

Many Wordpress programmer look at the last updated date of a plugin when chosing them for their site.
