### ISSUE TITLE
Fatal Error in Version 1.2.2

### ISSUE THREAD

**Issue by steffenster** [bueltge/Authenticator#28]
Die neue Version 1.2.2. erzeugt bei mir einen "PHP Fatal error:  Maximum function nesting level of '256' reached, aborting!". Ich habe es nicht gänzlich durchstiegen, aber ich glaube es geht darum, dass eine Endlosschleife erzeugt wird, ausgelöst durch diese Änderung: https://github.com/bueltge/Authenticator/commit/4585eaf14665e05b56df7c634d4b73befa595f67#diff-0ba20e669ae68b2d420f13f8f9fe61cbR27

**Comment by bueltge** [comment]
Hi @steffenster 
Danke dir, hatte wenige s vorher den Hinweis und gefixt. Sollte behoben sein, die Schleife bzgl __construct war der Fehler.
